name: PAC Scan - Test
on:
  workflow_dispatch:

env:
  IMAGE_NAME: demo:latest
  SCAN_NAME: ${{ github.run_number }}

jobs:
  PolicyAsaCode:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run scan to check configuration files for security issues
        uses: snyk/actions/iac@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            file: s3.tf
            args: --sarif-file-output=snyk.sarif --json-file-output=cicd_run_${{ env.SCAN_NAME }}.json
        continue-on-error: true

      - name: Upload result to GitHub Code Scanning
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

      # Step to capture final status after job completion
      - name: Capture scan result status
        if: always()  # Ensures this step runs regardless of success or failure
        id: scan_result
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "status=success" >> $GITHUB_ENV
          else
            echo "status=failure" >> $GITHUB_ENV
          fi
      - name: Upload JSON result and scan status to backend API
        if: always()  # This will ensure it runs no matter what
        run: |
          curl -X POST http://54.165.154.63:3000/cicd-status \
          -H "Content-Type: application/json" \
          -d '{"status": "${{env.status}}"}'  # or failure based on condition
